baseURL = "https://arpit-blog.netlify.com/"
languageCode = "en-us"
title = "Arpit Jain"
paginate = 3

DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

theme = "harbor"

[Author]
  name = "Arpit Jain"

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 3

[params]
  mainSections = ["post"] 
  favicon = "favicon.ico"

  [params.logo]
    url = "icon.png"
    width = 50
    height = 50
    alt = "Logo"